apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: app
        image: estebangaray/alta:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports: 
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: app
  type: LoadBalancer