name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: estebangaray/alta:latest
  deploy-to-cluster:
      name: deploy to cluster
      runs-on: ubuntu-latest
      needs: docker
      steps:
      - name: deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image --record deployment/my-app prueba-gha=estebangaray/alta:latest
      - name: verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.20"
        with:
          args: '"rollout status deployment/my-app"'
  ngrok-watcher:
      name: Ngrok watcher
      runs-on: ubuntu-latest
      needs: deploy-to-cluster
      steps:
      - name: Get ngrok URL
        id: getNgrokUrl
        uses: debianmaster/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.20"
        with:
          args: |
            URL=`kubectl -n prueba get ngrok -o=custom-columns='DATA:status.url' | tail -n1` 
            echo "::set-output name=url::$URL"